#!/usr/bin/env bash
# pve-sentinel install script (simplified standalone version)
# Runs inside the LXC container. Self-contained — no engine dependencies.
# Expects these env vars (set by ct/pve-sentinel.sh):
#   var_proxmox_host, var_proxmox_user, var_proxmox_token_name,
#   var_proxmox_token_value, var_opencode_api_key, var_nvd_api_key,
#   var_management_mode

set -euo pipefail

# Required values — prompt only when unset
if [[ -z "${var_proxmox_host:-}" ]]; then
  read -r -p "Proxmox host IP/FQDN: " var_proxmox_host
fi
if [[ -z "${var_proxmox_token_value:-}" ]]; then
  read -r -p "Proxmox API token value (UUID): " var_proxmox_token_value
fi
var_proxmox_host="${var_proxmox_host:-}"
var_proxmox_user="${var_proxmox_user:-sentinel@pve}"
var_proxmox_token_name="${var_proxmox_token_name:-sentinel}"
var_management_mode="${var_management_mode:-no}"

echo "==> Installing dependencies"
apt-get update -y
apt-get install -y git curl

echo "==> Installing uv"
curl -LsSf https://astral.sh/uv/install.sh | sh
export PATH="$HOME/.local/bin:$PATH"

echo "==> Cloning pve-sentinel"
git clone https://github.com/distantgeek/pve-sentinel /opt/pve-sentinel

echo "==> Installing Python dependencies"
cd /opt/pve-sentinel
uv sync

echo "==> Configuring pve-sentinel"
if [[ "${var_management_mode}" == "yes" ]]; then
  management_mode=true
else
  management_mode=false
fi
cat <<CONF >/opt/pve-sentinel/config.yaml
# pve-sentinel configuration (generated by the installer)
model:
  provider: opencode-go
  model_id: glm-5.1

guardrails:
  enabled: true
  preset: general

proxmox:
  host: "${var_proxmox_host}"
  user: "${var_proxmox_user}"
  token_name: "${var_proxmox_token_name}"
  token_value_env: PROXMOX_TOKEN_VALUE
  node: ""
  verify_ssl: false

cve:
  nvd_api_enabled: true
  mitre_api_enabled: true
  exploitdb_enabled: true
  pve_security_enabled: true
  pve_sa_feed_url: "https://pve.proxmox.com/wiki/Security_Advisories"
  nvd_rate_limit: 5

guests:
  vm_scanning: false
  lxc_scanning: true
  exclude: []

permissions:
  management_mode: ${management_mode}

storage:
  db_path: "sentinel.db"
CONF

{
  echo "PROXMOX_TOKEN_VALUE=${var_proxmox_token_value}"
  if [[ -n "${var_opencode_api_key:-}" ]]; then
    echo "OPENCODE_GO_API_KEY=${var_opencode_api_key}"
  fi
  if [[ -n "${var_nvd_api_key:-}" ]]; then
    echo "NVD_API_KEY=${var_nvd_api_key}"
  fi
} >/opt/pve-sentinel/.env
chmod 600 /opt/pve-sentinel/.env

echo "==> Creating services"
cat >/etc/systemd/system/pve-sentinel-scanner.service <<'SVC'
[Unit]
Description=pve-sentinel CVE scanner (daily host + LXC scan)
After=network-online.target

[Service]
Type=oneshot
WorkingDirectory=/opt/pve-sentinel
ExecStart=/opt/pve-sentinel/.venv/bin/python -m src.scanner_cli
Environment=PATH=/opt/pve-sentinel/.venv/bin
EnvironmentFile=/opt/pve-sentinel/.env

[Install]
WantedBy=multi-user.target
SVC
cat >/etc/systemd/system/pve-sentinel-scanner.timer <<'TMR'
[Unit]
Description=Daily pve-sentinel CVE scan
After=pve-sentinel-scanner.service

[Timer]
OnCalendar=daily
Persistent=true
RandomizedDelaySec=600

[Install]
WantedBy=timers.target
TMR
cat >/etc/systemd/system/pve-sentinel-digest.service <<'SVC'
[Unit]
Description=pve-sentinel CVE digest (weekly report)
After=network-online.target

[Service]
Type=oneshot
WorkingDirectory=/opt/pve-sentinel
ExecStart=/opt/pve-sentinel/.venv/bin/python -m src.scanner_cli
Environment=PATH=/opt/pve-sentinel/.venv/bin
EnvironmentFile=/opt/pve-sentinel/.env

[Install]
WantedBy=multi-user.target
SVC
cat >/etc/systemd/system/pve-sentinel-digest.timer <<'TMR'
[Unit]
Description=Weekly pve-sentinel CVE digest
After=pve-sentinel-scanner.service

[Timer]
OnCalendar=Mon *-*-* 08:00:00
Persistent=true
RandomizedDelaySec=300

[Install]
WantedBy=timers.target
TMR
systemctl enable -q --now pve-sentinel-scanner.timer
systemctl enable -q --now pve-sentinel-digest.timer

echo "==> Installing CLI wrapper"
cat >/usr/local/bin/pve-sentinel <<'WRAP'
#!/usr/bin/env bash
exec /opt/pve-sentinel/.venv/bin/python -m cli "$@"
WRAP
chmod +x /usr/local/bin/pve-sentinel

echo ""
echo "=============================================="
echo "pve-sentinel installed successfully!"
echo "Run 'pve-sentinel' to start the CLI"
echo "=============================================="
