#!/usr/bin/env bash

# Copyright (c) 2021-2026 community-scripts ORG
# Author: Kevbot (distantgeek)
# License: MIT | https://github.com/community-scripts/ProxmoxVED/raw/main/LICENSE
# Source: https://github.com/distantgeek/pve-sentinel

source /dev/stdin <<<"$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

# Required values — prompt only when unset, so unattended installs keep working.
if [[ -z "${var_proxmox_host:-}" ]]; then
  read -r -p "${TAB3}Proxmox host IP/FQDN: " var_proxmox_host
fi
if [[ -z "${var_proxmox_token_value:-}" ]]; then
  read -r -p "${TAB3}Proxmox API token value (UUID): " var_proxmox_token_value
fi
var_proxmox_host="${var_proxmox_host:-}"
var_proxmox_user="${var_proxmox_user:-sentinel@pve}"
var_proxmox_token_name="${var_proxmox_token_name:-sentinel}"
var_management_mode="${var_management_mode:-no}"

msg_info "Installing Dependencies"
$STD apt install -y git
msg_ok "Installed Dependencies"

setup_uv

msg_info "Cloning pve-sentinel"
$STD git clone https://github.com/distantgeek/pve-sentinel /opt/pve-sentinel
msg_ok "Cloned pve-sentinel"

msg_info "Installing Python Dependencies"
cd /opt/pve-sentinel
$STD uv sync
msg_ok "Installed Python Dependencies"

msg_info "Configuring pve-sentinel"
if [[ "${var_management_mode}" == "yes" ]]; then
  management_mode=true
else
  management_mode=false
fi
cat <<EOF >/opt/pve-sentinel/config.yaml
# pve-sentinel configuration (generated by the community-scripts installer)
model:
  provider: opencode-go
  model_id: glm-5.1

guardrails:
  enabled: true
  preset: general

proxmox:
  host: "${var_proxmox_host}"
  user: "${var_proxmox_user}"
  token_name: "${var_proxmox_token_name}"
  token_value_env: PROXMOX_TOKEN_VALUE
  node: ""
  verify_ssl: false

cve:
  nvd_api_enabled: true
  mitre_api_enabled: true
  exploitdb_enabled: true
  pve_security_enabled: true
  pve_sa_feed_url: "https://pve.proxmox.com/wiki/Security_Advisories"
  nvd_rate_limit: 5

guests:
  vm_scanning: false
  lxc_scanning: true
  exclude: []

permissions:
  management_mode: ${management_mode}

storage:
  db_path: "sentinel.db"
EOF

{
  echo "PROXMOX_TOKEN_VALUE=${var_proxmox_token_value}"
  if [[ -n "${var_opencode_api_key:-}" ]]; then
    echo "OPENCODE_GO_API_KEY=${var_opencode_api_key}"
  fi
  if [[ -n "${var_nvd_api_key:-}" ]]; then
    echo "NVD_API_KEY=${var_nvd_api_key}"
  fi
} >/opt/pve-sentinel/.env
chmod 600 /opt/pve-sentinel/.env
msg_ok "Configured pve-sentinel"

msg_info "Creating Services"
cat <<EOF >/etc/systemd/system/pve-sentinel-scanner.service
[Unit]
Description=pve-sentinel CVE scanner (daily host + LXC scan)
After=network-online.target

[Service]
Type=oneshot
WorkingDirectory=/opt/pve-sentinel
ExecStart=/opt/pve-sentinel/.venv/bin/python -m src.scanner_cli
Environment=PATH=/opt/pve-sentinel/.venv/bin
EnvironmentFile=/opt/pve-sentinel/.env

[Install]
WantedBy=multi-user.target
EOF
cat <<EOF >/etc/systemd/system/pve-sentinel-scanner.timer
[Unit]
Description=Daily pve-sentinel CVE scan
After=pve-sentinel-scanner.service

[Timer]
OnCalendar=daily
Persistent=true
RandomizedDelaySec=600

[Install]
WantedBy=timers.target
EOF
cat <<EOF >/etc/systemd/system/pve-sentinel-digest.service
[Unit]
Description=pve-sentinel CVE digest (weekly report)
After=network-online.target

[Service]
Type=oneshot
WorkingDirectory=/opt/pve-sentinel
ExecStart=/opt/pve-sentinel/.venv/bin/python -m src.scanner_cli
Environment=PATH=/opt/pve-sentinel/.venv/bin
EnvironmentFile=/opt/pve-sentinel/.env

[Install]
WantedBy=multi-user.target
EOF
cat <<EOF >/etc/systemd/system/pve-sentinel-digest.timer
[Unit]
Description=Weekly pve-sentinel CVE digest
After=pve-sentinel-scanner.service

[Timer]
OnCalendar=Mon *-*-* 08:00:00
Persistent=true
RandomizedDelaySec=300

[Install]
WantedBy=timers.target
EOF
systemctl enable -q --now pve-sentinel-scanner.timer
systemctl enable -q --now pve-sentinel-digest.timer
msg_ok "Created Services"

msg_info "Installing CLI Wrapper"
cat <<EOF >/usr/local/bin/pve-sentinel
#!/usr/bin/env bash
exec /opt/pve-sentinel/.venv/bin/python -m cli "\$@"
EOF
chmod +x /usr/local/bin/pve-sentinel
msg_ok "Installed CLI Wrapper"

motd_ssh
customize
cleanup_lxc
